#/*******************************************************************************
 # Copyright (C) 2011, Linaro Limited.
 #
 # This file is part of PM QA.
 #
 # All rights reserved. This program and the accompanying materials
 # are made available under the terms of the Eclipse Public License v1.0
 # which accompanies this distribution, and is available at
 # http://www.eclipse.org/legal/epl-v10.html
 #
 # Contributors:
 #     Amit Daniel <amit.kachhap@linaro.org>
 #       - initial API and implementation
 #
 #     Torez Smith <torez.smith@linaro.org> (IBM Corporation)
 #       - editorial and/or harness conformance changes
 #******************************************************************************/

CC=gcc 
CFLAGS=-Wall

all: test_usb_cpuidle

clean:
	rm -f test_usb_cpuidle test_usb_cpuidle.o



